
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding-ebf
resources:
  - ../../base/linkding
  - tunnel-token.yaml
  - tunnel.yaml

patches:
  - path: namespace-patch.yaml
    target:
      kind: Namespace
      name: linkding
