apiVersion: v1
kind: Secret
metadata:
    name: ghost-config
    labels:
        app: ghost
type: Opaque
stringData:
    config.production.json: ENC[AES256_GCM,data:rFSvqZ16VO5lvmYSA8KVdekPZJtHanO30AqYmPG6Rp0I6EIOnmnp1ElC2bRZK/F6OVWTlmcVIrfqhnuR/9EUKRFZX47eVrc3tv1j226wFoyvEMR8NehKbn0wD05OZR6VUFdKDFxlNixvnIjhyfnKBOexN5aP05K2HHJuIb0imQvsK5w2PLYrZI+UV111+Z+fjvbNbnf0HMZhjWQbbhB/aBPlnhPvhyfpUBXkoyZ/RZb4aYNxRBYM9LiPW2CqjTYTXfBzWBRwDV72bhQe87j10+FL8kzGwQVfdqn+P53yVqIBsw+vQfGWAWr747vTGSWvxuOiOxxqasB9UaYFT3I+6H6ULpATzBM7TPfjkOfilmZ2KbVIriC+1WYp6MaJhM797SE/N7/1npFFIMfedydnAkCkzL50o7JI7dBgNwVQbrRu3CrxvyFjyv4qCaXA8V5ASoYJxk8EKt2m5fkoNGS2dGsKK6tVJmJP4Eey/9nTDXTYzCYJElY4+GBNW6hctf19izm1mdOSXkEqRyLxvMv1RBfvTghHOSa4u9yhSZ6JtpXZtG4XNZ00zQUP2Izfylsab3gjfzebWtT6X33kzOh9hQqCgeE2WQIoiZw/KnkO3CRbLFs1Uy9uxtRC8YXHzrt/NGMXja+7FA4L41Uqv1tt2Nmzo+NzdO1W3/ZXCsTo1bIiFnTxm1T4q13DmD1J+xL1V5L7Bsitc+L0Bd66E1acv48NDvYq+ajhrZ21gGxm+dAVvW2RkEoIHZeSZkXkivCSVhCPuvtNzceWUI3pE5ayk1CMhSZRGkzqFe2LGEX6IYd5epUXFIrulG42yVYJ9By297pokTaF6dKcpfEuZaRJCr9qUNgqk623epL7DOdIo2QHxG4HCnUOq0dDE5XyVeWTTNlD/ZFohliWlABB++Z+zYNu8a9RxsLyuV9GVB9tTT5mSVkYu/At9BWnatuTXME2MWaSid91urlNPHxx60AmtSJ6xa/s+0AjBw2U7RtQLldqAMv0aiFYosmi/qI8AMcf3Xt8ETzCcS2rkHomy73kRpXkffHvKcMXITqYp1D6PrgZUcGVxh4+7FtOjA==,iv:ctYqVPVWaLMCBVmPjBScdxIckA2p1/yUZzU/7SVtwcE=,tag:jUBhOjWN5yTv+9kCbrz5+Q==,type:str]
sops:
    age:
        - recipient: age1dknxwrzsnv2aq7lar4jznk89wrv7hfcjc0cmj9tf5kkcsqwptgeq3zw0lu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWTM5cFZnVzJveENJTDJi
            dDdMczYwTHJSVVJjU0ljUkxvSjMvQjFmODNFCnVicnh1dzBmUC9yWjYvRWNLWExy
            YlBXbmZvSS9ucWs2SVZDSWVVK0VOSGcKLS0tIElWTk52c0pFYk1GbEx0b2hhbjMy
            V0R6TXNYcHFFaXduQmE5WDBvV3lvRlkKGswVNwwEceMIeQesBtQMQNzVJ/1+JMXg
            r1GIUpY6cuUejDm1DApN184UXbfuNL30taqUFKjpebQymkPsA+KYxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-11T05:45:15Z"
    mac: ENC[AES256_GCM,data:8LAo+WQmpeIAuzxiiAwyFsobWsJUIcX1+oFQP5yLQBd7Xbo+3V33+uwFRkTuZthlb7P45dJNnzyrT8NPOnYPI0Ruf+qGehWhUKX0OiLNMRCKU89Gg3l0QJMr12ByfKm+HfJsW67DmgPN9TUIjF77+3f5OVAB9IdrCmpVDP1ieBk=,iv:njcxXrSPLSKuaWTDyPxQngwEn+r+qtTcOg8gkXE1zH0=,tag:89zFmeeoqwnlGPsvmUzW2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
