apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ghost-ebf
resources:
  - ../../base/ghost/
  - ghost-config.yaml
  - tunnel-token.yaml

patches:
  - path: namespace-patch.yaml
    target:
      kind: Namespace
      name: ghost
