apiVersion: v1
kind: Secret
metadata:
    name: ghost-config
    labels:
        app: ghost
type: Opaque
stringData:
    config.production.json: ENC[AES256_GCM,data:C0Udlm00VWmDMAwLQGQNszAFxqnsK3S4zWCCcpPyJy+Gw2ncs82YTV4fHB8TkKRhaK1WozAIZi6eJpIi6rAsjgSRDfBoNqJL552GGmsKnjNIEBWP3+3kXpWXWeCQHCFu/+T1wSjOae9C3tFew5b9KV2EI20+jNSFVD/QLzey/xrG9unPeeTaJQ+nx9vcrztbBeAn0gOVY8G4+4nTujdl044v2dQm3HsRqbvHX2w8nuMySRJV7DDdwAvNnDvzYLuOsYBHNf6v1L08MNpDoku8YWZ0RNsPJ3KdwBR/VCsR2OtHS8t3NqPeWC47ZUoR7bzO4eR8hjeRKizZChMH9AYN5mYvPqztprPkqZpbeFv5wdGIv04BKTe4C3lKk+f8vwSFnoInit2aBr2IiHKZaAZNCzg0G/waQlKLONudBJyvUvSIsWzIj5JxH5pcbFocZvzU5bPx5sadonb9N3FaJIRE578qzrZrZiZXDWVZZVCKb1pTvj86ohb+PjDpQs2B4KcR54Id+LOheCsXItLQIEyqK2LyvYS7wLPHCoaLkpk+JZPDFi9wxvq04b9VUAphRI9fEpehmW6MjXGTD7j2xzAu9478BwQjIWufgrvDQ1OO3Dy+R9ufEV4sVv+pLR0iZxgyEGuNi6+Im7ShP76bsijyVs0kZ73PZNqqBYcmyn1S37WVJQ89VLTqxVjYgejy8denDhDlRnF5C5wQISzf3A5+vfayKGq3xMlBnfLRmvJvbT/m1qyDkTkg/PlwqHJr6vQ9M3kzeFYI8U39wjdwJSBG0MCmMmSseMM1+6wVKVNeVODl6SXG7KcAEMKRzCBd/CsJmvZ3NEgC1slkl5NTnEEdz59QXwk5YpOY7JQxRf7OwYKEwfRdOuFGPzG+VfbF0jXCBfHxrVRMb2/nHDzUDvWMyJw9gNG4gLO4lEh5+8mNFYotIyr3/Odbkdmpu0JjE4MZjg1T7FOK36bapjMn123pI4/BpFtJWhI2AosDQRqoadZLi0yzOSh7/qQ6+UrDXnpsPHOK4arz8R7pULVJf5ke2qZYwTHfYleN,iv:Tdwkgju7HlLrISw/fKkEezVjqTh8dd6V0sYcv/Uvk5M=,tag:poxJjbrA0QVymgBfTN8qiw==,type:str]
sops:
    age:
        - recipient: age1dknxwrzsnv2aq7lar4jznk89wrv7hfcjc0cmj9tf5kkcsqwptgeq3zw0lu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1c202VzZpV0oxczcxek52
            Z2dNby9NZGJSVUxUY1NIT3Y0T2Z6ZkVhM3drClUrdDY2dlFtQlV4SlRrN3hsYzNj
            RUlTNTd1VkZzQ2xNOTVLZ0o3V3pNWGsKLS0tIEliSEwrL3NSbUttZXYzZTdKdGUy
            djEyUUNsb1JTZjFreUNZL05SSGNCSG8KTTZJfTdzvTi4zJfCheR4Znbs7pylsB68
            DvxMrgENb0PgCPCoKWez8lKvHSfwCzuY6SlSNCWcOMWI7xYOHdWbxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-09T17:13:18Z"
    mac: ENC[AES256_GCM,data:kHfGdqmWFL08cGBlGPKH3dmnylkVQ5ojJYhf+5SoIceZEQJVCCnATbsAFGe70h9OInqkVTRQWVSTd2XIDE5QbkWnquRfYk3pvbkrs/pmnpP4/5KYmU8PLtNCCL2MbYpY1DxjP0h2Mit7jTTMpo2evT9lo0jrRrm0XVGNC/Jdz00=,iv:Rl6smiuaLoFsuR/FwpQMSWTahnokET4agDB3mXobSyU=,tag:HDN+0n0+asH8CY69xLFtYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
