apiVersion: v1
kind: Secret
metadata:
    name: ghost-config
    labels:
        app: ghost
type: Opaque
stringData:
    config.production.json: ENC[AES256_GCM,data:qvrgZSa65qLynKSsOa+rveaQ9/xghdXFNEmS0/w35u1CF89xEALrW3YAKXbyCQppubgXv61GnTmy9PtkKnnukSTGrj6xrB84/BZhb0SnL7lnR/Cnhxy4AlqKWsTKEHWfqVfo40HcdLrpwFKRJKnut/UKKiJaEXMVuz8/ewJnnqs9zd2VvOvHt551xVOLsEBCPZoXwgNobLVdB7cdUHcdH+Jq0ST7sJxCbdI5qB//J1BIuP+cAI9Z1RHf0W16smcxSHsDa9FZDj/797WgL1KLgbJodNsQ5dGk1Cjq2o3Mz2BNhNKSGoqXvyty2GTypHAMRrh95g2ZfYf6ljGNf++LNxz0UIE2tVx4arGvNBcklWvR7AwOeE1KqaE5xQLR4rz8/fEC+c4fbbUlq/CbQPk+lmPXyfeYjnXNXejNiEUXWK/kh7vU6FXu+8bOUWV042QRDrZi1z76k/I5Un1lm5+Ck52zkmxj3gn7eL9u78UjOqY9YGSTmJ4s4q/fIa9dXa4wP+hB0snk/TNDVo27QIsHTN68ciNVSf7ENN5aglEIm0NTCM9rZb14xfaZ4ddhBgxzB7Td6cMMj9u4pmtu2jfYi3cDtXOEj+yfGblemhHZT7oFE6mshAlvN7rq+04rixKImZQ25mUcyWpgpcf+ThXdKcboKWwS6zMX+SpgU3DKWto7SGNLEJuO+8Itzyig+oAxDqzOZaUtyOhQNGbEH7A+kQlRNGXIMRPiU+jaPifj1/zED9qMLyMzcqzgdhQ53ZrxC9ZmcPEMrShgPiemo5AY7MhztE8NPFBwWWzaS5YXV7ZA23OaZqLootzNgZNLBPiy5AVM7lQ7Dl8ZRTB/vf4F/jrbRJ1dFJjsXQ+HxKH+EUFqJkQSvspfIpAs/85V1v9iJUrKADChgJ9XpiJ3wVoeO6tDAFoh3liNanFeZ6W+3eZO0PXDgtemie/TXfzpp6UiEWb5opw47Uk/7w==,iv:d0ZTIzwWZicoHRHgxczXJVFBc2I6GxqZ+0ffrodw1ME=,tag:qGO3ZfwSVFMIKhby04B3aw==,type:str]
sops:
    age:
        - recipient: age1dknxwrzsnv2aq7lar4jznk89wrv7hfcjc0cmj9tf5kkcsqwptgeq3zw0lu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNlVyRVlqdW8wclpPaXZt
            T3RoOXU5b1lHeE0xa0ZOcDV5YzFGakUwd3c0ClIvdFlsdk1aSC9jbHRLelJGRU5W
            aTlZMXIzZ2VDcW1nZi9WOFpIT2dXTGcKLS0tIHVyS1l0VHVaV3ZYZ3p4ZDlyU21K
            VHpNMjc0QVhvK3hLWUxDWkZVeEFJc28K30MQqswOWmX6w7zlA76jDLchRnZBsVDU
            avg16JsfsWkfQthNN+uZrqXI7MIvfhJLGqh0yo4bdEVwydfveKxekA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-09T16:49:47Z"
    mac: ENC[AES256_GCM,data:6C+rcW/V19xVv9DzV/pNAQEePqISLPYJwCy60HDTH7bVwAqmU0ThkRHU1Zms2PBVr0/n7zwEyM90gSjPy7dWAsHRQaeHi5mBDFtL4iHgmewGAjbMwqmvnNcxzzStnTsFf9yoFgToQ3NHC28fRPQ5LNOvAkvZKc/RpJ2nysO5aVE=,iv:tNrvlEnLFzneUWEa2yA4k8FZzsR6Hg5GlYMXhBb8scc=,tag:CgXwSu77Fq1MbUEstyuOWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
