apiVersion: v1
kind: Secret
metadata:
    name: ghost-config
    labels:
        app: ghost
type: Opaque
stringData:
    config.production.json: |-
        {
          "url": "https://ghost.lam-lab.cc",
          "admin": {
            "url": "https://ghost.lam-lab.cc"
          },
          "server": {
            "port": 2368,
            "host": "0.0.0.0"
          },
          "mail": {
            "transport": "SMTP",
            "from": "isaacisaaclhk@gmail.com",
            "options": {
              "service": "Google",
              "host": "smtp.gmail.com",
              "port": 465,
              "secure": true,
              "auth": {
                "user": "isaacisaaclhk@gmail.com",
                "pass": "fxzb hmbu idwi wvtz"
              }
            }
          },
          "logging": {
            "transports": [
              "stdout"
            ]
          },
          "database": {
            "client": "mysql",
            "connection":
            {
              "host": "mysql-service",
              "user": "user",
              "password": "password",
              "database": "ghost",
              "port": "3306"
            }
          },
           "paths": {
             "contentPath": "/var/lib/ghost/content"
          }
        }
