apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  - mysql-config.yaml
  - mysql.yaml
  - ghost-deployment.yaml
  - service.yaml
  - tunnel.yaml

