apiVersion: v1
kind: Secret
metadata:
    name: mysql-env
type: Opaque
stringData:
    MYSQL_DATABASE: ENC[AES256_GCM,data:57c7oYI=,iv:o/pzX31eA/BdLKKXacpyK0s0BjqjTSKLHt80HwMn60U=,tag:Hzn97TOy3Don/gLgPjPx7A==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:6WO4jg==,iv:z6FjikMl7yDscNGIACMM4A34yStWRudaAl7BEsMVt3w=,tag:0aJK22FR26kT4/O/Y6B5ug==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:OOpVWDvvcgg=,iv:VJsJSB3dKXaXitpmb9/oGE/QVzFc0OSLnc4Df7KPFBw=,tag:xD4z3nD9/T5B/5Fp6el4RQ==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:l4FlGjkpLWP10ZrS6w==,iv:5wx0cIMtx3pYtLQpRBY8iKIAm8oKvrKMKuGQn807plA=,tag:CvF9RQRSY7RX3YJXUwzMPw==,type:str]
sops:
    age:
        - recipient: age1dknxwrzsnv2aq7lar4jznk89wrv7hfcjc0cmj9tf5kkcsqwptgeq3zw0lu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSE14ZzUrYngrMmwvK2ht
            S0hWT2xINEZTTXhzbUMzcm8yd1dCN09panlVCm9rRHhKaDU1VXRSelV5eStVOXEv
            RG1UZkNydHhHWnlLbVZKV1ROcEVLZGMKLS0tIGVvdm56TE1GSlJOMmZ4VHpQa2pP
            YWgyWE51dUlhYnhqdXIySFlpZ1JuWXcKnvMG51xQuNvEoW0hvgLUzLOqGDXJ8lND
            7L0C1igCd0FQi2REv/pPhuYopN0slZ79d2qIl+seNaDlkKRAa4UlvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-09T16:05:53Z"
    mac: ENC[AES256_GCM,data:BAmJ/ExsHkY9wHmHgHj478wKrPgoPkTYGL4bCX9Su/MAQKG4BmYEJkIJaSsC4IHYjUSMFjjH605i4m+BLs8wndSYr+VwXMuWfXfNt1retyOabd+TFlO2mjYQ/Y+tq6+yNpVGJTsDOdw0E+0VboFBqGpq+Yl/tvLjgXMjaZZALDg=,iv:NpyDAl06THBzWAcXpW6FPV20XONtNfnybSSM4L2tnfQ=,tag:zfbZNenqmFst6t8lfOZUfA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
