apiVersion: v1
kind: Secret
metadata:
    name: ghost-config
    labels:
        app: ghost
type: Opaque
stringData:
    config.production.json: ENC[AES256_GCM,data:n91DlA3jg1a4Js8bv4BPscFCxT3H3hRpWeZJ8mo3jr+jl6/YtlXOVBcy/Y60MHTZnBkVmEI6oi5mADdCex2dUmvpdOfBkb4gMUuGeedoxJLPkpU9eqX2IhiPKqyx0+qkzGSNMXy7y2mO858kwytR8kcE7spq9h09yQ09qkYEqd6o3kbAAqbPAD1yY2PHy9j1Rhxy6bDx0b2KNCPmZoVQFTXZIgJbO5zZXfVLrC0p6MguvTyg+rJASWBJKEBo42QY+7PvmR7nv8UVVRGxzBWRlgebgt8Q/sVLsykz8CG9jY5ixg/1KpVtGYpnldeCe7RIIsNbklFa1ZroCKLwAYEHaeU1vBbVbs46sbv8CuuMlsCe81DhAQPwsfJlAv2ZkdFiT3fIye0G+Pa+rxvusbGU/OwfgqkFHZx3edV2fygfc4HdmY1+bGUh1pUdCEQ3ocozbeDQmd3CMQvRdqVdJF5PoglUyMyqsKHPlcCXq+t5LXi/2+jwEed/bkc29mlMTMOvYEbL0h0nvdl6eaS8Fami/wLpKQVXn9AYdpSd9JSOcPXW/oiayxGrPw+2edoZDa5P65keZmE1ZkDd6YDgM7ZNvUNuFLg2ELxjUBPknkXtq3JVgp9FWBsNMTiRAlYULL9AyNJPA6EekVR1zg7EL9OlnnwjeAyWyqXz4FrClc7FyhFrrJcTNXbDhD5vhXs4cBqoPq7iK+PVmWljTBPIMpn0vT4X7SgmFmyK/FoxeQwtyo2oxf6iKT2seliUuQh6J4W7M3NqQdaNrVpIwT5D9Cxmq6kSRDoHo6121eqfCifMSRHKAQnKhHnCa4jUYXY4IRhj6VfV8VPs/Wl2I7f29FYVvf+RXR3bJuqDrMGSQTYH7qFoWOXqSL4yw796wwbcB3AMeBXaINM1Pt0ZqRCHI4cyfqFxgfZeiOOhsff3g2P3Obdi+FYjLEuu2nHv2w+JkKcRwuvaxRFEYEmfD6KNjLrU86s8piOXcEA7l+/ShhqKVcQer3j/801q1smfLI/OOwXGC3xnl2HmuRh/gO38H/rXDzfnJyrV3MNTew==,iv:oHbcCI2oK/vQ4d5xeJSNPWPB2riv0e5VCu0FkvN1wIo=,tag:mciPKnwz+7kNh/9WVodhig==,type:str]
sops:
    age:
        - recipient: age1dknxwrzsnv2aq7lar4jznk89wrv7hfcjc0cmj9tf5kkcsqwptgeq3zw0lu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbEZISzZOMVJVVWNFMXcy
            cmNSbCtoZGo4TjhXVXpsU01xQndkS2lKRjJjCjdPRWx1Q0VtMWtIejBJL245bDFa
            VkFQRG1UNkszb3dWSUpPV29nQytrckUKLS0tIHBlVEpsZHlRYTRzTTlmVUtlSDA3
            OStWREFHbW4vYnNEaDFoZlJDaGVPTUkKDptumpY3tF2jtvixcbls9zatRMSggKXg
            e2NjQlcRW7Ing8ol2TtSTX5tBnpJo+tXXvC+drBnrDIJCym8hFOsyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-10T16:39:09Z"
    mac: ENC[AES256_GCM,data:yBOjhebqRQnz+uQJ7By3BkWaGT/1g4x6cimfgLXxj+xY0zXsMp3BaBB4Xcvv3VOIifNC7Q10kv9E5qNCeX8s2+6l6Mna3VbjYlX3EBJJm+Uzk9XH9evc/jFC/XOimPTptVbw9CP6SDn1XXGnQEPZQI9LqS5aXJ86zSqTSA08rWw=,iv:QOqiDYbzDqDTqPSOs9hZLA2UOPTzvxyNeLC2dsGlRrg=,tag:W5nsaYOHbeP4ahA4r6YlvA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
