
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audiobookshelf-ebf
resources:
  - ../../base/audiobookshelf/
  - tunnel.yaml
  - tunnel-token.yaml

patches:
  - path: namespace-patch.yaml
    target:
      kind: Namespace
      name: audiobookshelf
