apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: audiobookshelf
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - image: ghcr.io/advplyr/audiobookshelf:2.30.0
        name: audiobookshelf
        ports:
        - containerPort: 3005
        envFrom:
          - configMapRef:
              name: audiobookshelf-env
        volumeMounts:
          - mountPath: "/metadata"
            name: metadata-data
          - mountPath: "/config"
            name: config-data
          - mountPath: "/audiobooks"
            name: audiobooks-data
          - mountPath: "/books"
            name: books-data
          - mountPath: "/podcasts"
            name: podcasts-data
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
      volumes:
        - name: config-data
          persistentVolumeClaim:
            claimName: config-pvc
        - name: metadata-data
          persistentVolumeClaim:
            claimName: metadata-pvc
        - name: audiobooks-data
          persistentVolumeClaim:
            claimName: audiobooks-pvc
        - name: books-data
          persistentVolumeClaim:
            claimName: books-pvc
        - name: podcasts-data
          persistentVolumeClaim:
            claimName: podcasts-pvc

